ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.garamohamed.ApplicationKt.module

database:
  url: jdbc:postgresql://localhost:5433/marketplace
  user: postgres
  password: postgres
  driver: org.postgresql.Driver
